<?php
if ($this->isActive()){
    if ($this->isCool()){

?>       

		<!-- Start LiveHelp Code Copyright 1997 - 2015 www.livehelp.it Sostanza srl  -->        
		<SCRIPT language=javascript> function apri_livehelp() {var d=new Date(); nuovo_LiveHelp_<?php  echo $this->getLivehelpID(); ?>=window.open('http://server.livehelp.it/client_user_resp/?provenienza='+ escape(document.location.href) +'&info=&template=10314&stanza=&ID=<?php echo $this->getLivehelpID(); ?>&gruppo=Assistenza&nick=&x=' + d.valueOf(),'LiveHelpwin1_<?php echo $this->getLivehelpID(); ?>', 'status=no,location=no,toolbar=no,width=600,height=465,resizable=yes'); nuovo_LiveHelp_<?php echo $this->getLivehelpID(); ?>.focus();} </SCRIPT>        
<?php
        if ($this->getPosition() != "0"){
			if ($this->getPosition() == "1"){
				$span = "<span  id='LH2013'>";
			}
			if ($this->getPosition() == "2"){
				$span = "<span style='display:block; bottom:0px; right:0px;  position:fixed;z-index:15000;' id='LH2013'>";
			}
			if ($this->getPosition() == "3"){
				$span = "<span style='display:block; bottom:0px; left:0px;   position:fixed;z-index:15000;' id='LH2013'>";
			}
			echo $span;?>
			<A HREF="#" OnClick="apri_livehelp(); return(false);"><img border="0" src="http://server.livehelp.it/admin/logo_livehelp.asp?bottone=<?php echo $this->getButton(); ?>&gruppo=<?php echo $this->getLivehelpID(); ?>&stanza="></A></span>        
			<!-- End LiveHelp code -->    
		<?php }?>
 <?php
    }else{
	
	    if ($this->getDynamic()!="0"){
?>      
 <!-- Start LiveHelp activation widget - http://www.livehelp.it -->       
		 <script type="text/javascript">        
		 function LHready(){if(document.readyState == "complete"){(function(){ var lh=document.createElement("script");
		 lh.type="text/javascript"; lh.async=true;
		 lh.src="//server.livehelp.it/widgetjs/<?php echo $this->getLivehelpID(); ?>/<?php echo $this->getDynamic(); ?>.js?x=" + 1*new Date();
		 var node=document.getElementsByTagName("script")[0];
		 node.parentNode.insertBefore(lh,node);
		 })();} else {setTimeout('LHready()',150);}} LHready();
		 </script>          
<?php
		}
   }
}?>