<?php
    //get the page

    $success = Mage::app()->getRequest()->getActionName();
    if($this->isActive()) {
        $confronto = $this->getViewLH();
        $view = FALSE;
        $vars = [];
        $tutto = $this->getDynamic();
        $vars["gen"] = $this->getGEN();
        $vars["cat"] = $this->getCAT();
        $vars["prod"] = $this->getPROD();
        $vars["funnel"] = $this->getFUNNEL();
        $module = "";
        $controller = "";
        $action = "";

        if($this->check_vars($vars) && $tutto != "0") {
            $view = TRUE;
            $idLH = $tutto;
        }
        else {

            if($vars["funnel"] != "0") {

                $request = $this->getRequest();
                $module = $request->getModuleName();
                $controller = $request->getControllerName();
                $action = $request->getActionName();
                if($module == 'checkout' && ($controller == 'cart' || $controller == 'onepage') && $action == 'index' || ($success == "success")) {

                    $view = TRUE;
                    $idLH = $vars["funnel"];
                }
            }
            if($vars["prod"] != "0") {
                $product = Mage::registry('product');
                if($product && $product->getId()) {
                    $view = TRUE;

                    $idLH = $vars["prod"];
                }
            }
            if($vars["cat"] != "0") {
                $category = Mage::registry('current_category');
                $product = Mage::registry('product');
                if(($category && $category->getId()) && !($product && $product->getId())) {
                    $view = TRUE;

                    $idLH = $vars["cat"];
                }
            }
            if($vars["gen"] != "0") {

                $category = Mage::registry('current_category');
                $product = Mage::registry('product');
                $request = $this->getRequest();
                $module = $request->getModuleName();
                $controller = $request->getControllerName();
                $action = $request->getActionName();

                if(!($module == 'checkout' && ($controller == 'cart' || $controller == 'onepage') && $action == 'index' || ($success == "success")) && (!($category && $category->getId()) && !($product && $product->getId()))) {

                    $view = TRUE;
                    $idLH = $vars["gen"];
                }
            }
        }
        //voglio tracciare gli ordini conclusi grazie alla chat
        if($this->trackOrder() != "0") {
            if($success == "success") {
                echo $this->trackCustomerOrder();
            }
        }

        if($view == TRUE) {

            $MAGENTOcart = "";

            //vuole vedere il contenuto del carrello o l'id dell'utente se loggato
            if($this->getCart() != "0") {
                $MAGENTOcart = Mage::getUrl() . "livehelp/index/getcartlhinfo";
            }

            ?>
            <!-- Start LiveHelp Magento activation widget - http://www.livehelp.it -->
            <script type="text/javascript">
                var LHmagento = '<?php echo $MAGENTOcart ?>';
                var LHinfo = '';
                function LHready() {
                    var lh = document.createElement("script");
                    lh.type = "text/javascript";
                    lh.async = true;
                    lh.src = "//server.livehelp.it/widgetjs/<?php echo $this->getLivehelpID(); ?>/<?php echo $idLH; ?>.js?x=" + 1 * new Date();
                    var node = document.getElementsByTagName("script")[0];
                    node.parentNode.insertBefore(lh, node);
                }

                document.addEventListener('DOMContentLoaded', LHready, false);
            </script>
            <?php
        }

    } ?>