<?php
//get the page
$success= Mage::app()->getRequest()->getActionName();
if ($this->isActive()){
	
		$MAGENTOcart="";
	
		//vuole vedere cosa c'è nel carrello o l'id dell'utente se loggato
		if ($this->getCart()!="0")
		{								
			$MAGENTOcart=Mage::getUrl()."livehelp/index/getcartlhinfo";				
		}
		
		//voglio tracciare gli ordini conclusi grazie alla chat
		if ($this->trackOrder()!="0")
		{
			if ($success=="success")
			{
				echo $this->trackCustomerOrder();						
			}			
		}?>      
		<!-- Start LiveHelp Magento activation widget - http://www.livehelp.it -->       
		<script type="text/javascript"> 
			var LHmagento='<?php echo $MAGENTOcart ?>';				 
			function LHready(){if(document.readyState == "complete"){(function(){ var lh=document.createElement("script");
			lh.type="text/javascript"; lh.async=true;
			lh.src="//server.livehelp.it/widgetjs/<?php echo $this->getLivehelpID(); ?>/<?php echo $this->getDynamic(); ?>.js?x=" + 1*new Date();
			var node=document.getElementsByTagName("script")[0];
			node.parentNode.insertBefore(lh,node);
			})();} else {setTimeout('LHready()',150);}} LHready();
		</script>          
	<?php
	
}?>